# Generated by Django 6.0.8 on 2026-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularlesson',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='regularlesson',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
