# Generated by Django 6.0.8 on 2026-08-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_regularlesson_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='paid_status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено учнем'), ('confirmed', 'Підтверджено вчителем')], default='pending', max_length=15),
        ),
    ]
