# Generated by Django 6.0.8 on 2026-08-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_slot_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено учнем'), ('confirmed', 'Підтверджено вчителем')], default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Заброньовано'), ('cancelled', 'Скасовано')], default='booked', max_length=15, null=True),
        ),
    ]
