# Generated by Django 6.0.8 on 2026-08-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_slot_is_break_alter_slot_paid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
