# Generated by Django 6.0.8 on 2026-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_slot_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='is_break',
        ),
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Заброньовано'), ('cancelled', 'Скасовано'), ('break', 'Перерва')], default='booked', max_length=15, null=True),
        ),
    ]
