# Generated by Django 6.0.8 on 2026-08-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_remove_slot_is_break_alter_slot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('booked', 'Заброньовано'), ('cancelled', 'Скасовано'), ('break', 'Перерва')], default='booked', max_length=15),
        ),
    ]
