# Generated by Django 6.0.8 on 2026-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_action_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlessonduration',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='teacherstudent',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
