# Generated by Django 6.0.8 on 2026-08-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherlessonduration_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
