# Generated by Django 6.0.8 on 2026-08-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherstudent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
