# Generated by Django 6.0.8 on 2026-08-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teacherstudent_price'),
        ('scheduling', '0007_alter_slot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('credit', 'Нарахування вчителем'), ('debit', 'Списання за урок'), ('refund', 'Повернення за скасування')], max_length=20)),
                ('amount', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='scheduling.slot')),
                ('teacher_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='accounts.teacherstudent')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
