# Generated by Django 6.0.8 on 2026-08-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_balanceaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='action',
            name='accounts_ac_created_ecacea_idx',
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='accounts_ac_target__d7e79e_idx',
        ),
        migrations.AlterField(
            model_name='balanceaction',
            name='action_type',
            field=models.CharField(choices=[('credit', 'Нарахування вчителем'), ('debit', 'Списання за урок'), ('refund', 'Скасований урок'), ('restore', 'Відновлення уроку')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
